// Auto-generated by `gravity new`
// This build script generates static Rust code from .gravity UI files

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Get output directory for generated code
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(&out_dir);

    // Find all .gravity files in src/ui/
    let ui_dir = PathBuf::from("src/ui");
    if !ui_dir.exists() {
        eprintln!("Warning: src/ui/ directory not found, skipping code generation");
        return;
    }

    let gravity_files = find_gravity_files(&ui_dir);

    if gravity_files.is_empty() {
        eprintln!("Warning: No .gravity files found in src/ui/");
        return;
    }

    println!("cargo:rerun-if-changed=src/ui/");

    // Generate code for all .gravity files
    let mut generated = String::new();
    generated.push_str("// Auto-generated - DO NOT EDIT\n");
    generated.push_str("// Regenerate with: cargo build\n\n");

    for file in &gravity_files {
        println!("cargo:rerun-if-changed={}", file.display());

        // TODO: Parse XML and generate code
        // This is a placeholder - actual implementation will use gravity-core parser
        generated.push_str(&format!("// Generated from: {}\n", file.display()));
    }

    // Write generated code
    let output_file = out_path.join("ui_generated.rs");
    fs::write(&output_file, &generated).expect("Failed to write generated code");

    // Expose path to generated code
    println!(
        "cargo:rustc-env=GRAVITY_GENERATED={}",
        output_file.display()
    );

    println!("Generated UI code from {} files", gravity_files.len());
}

/// Recursively find all .gravity files in a directory
fn find_gravity_files(dir: &PathBuf) -> Vec<PathBuf> {
    let mut files = Vec::new();

    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(find_gravity_files(&path));
            } else if path.extension().and_then(|s| s.to_str()) == Some("gravity") {
                files.push(path);
            }
        }
    }

    files
}
