// TreeView widget demo UI module.
//
// This file auto-loads the corresponding tree_view.dampen XML file.

use dampen_core::{AppState, HandlerRegistry};
use dampen_macros::{UiModel, dampen_ui};
use serde::{Deserialize, Serialize};

// Import Message and CurrentView from the parent module (generated by macro)
use crate::{CurrentView, Message};

/// Tree node data structure
#[derive(Default, Clone, Debug, Serialize, Deserialize)]
pub struct TreeNode {
    pub id: String,
    pub label: String,
    pub icon: Option<String>,
    pub children: Vec<TreeNode>,
}

impl TreeNode {
    pub fn new(id: &str, label: &str) -> Self {
        Self {
            id: id.to_string(),
            label: label.to_string(),
            icon: None,
            children: Vec::new(),
        }
    }

    pub fn with_icon(mut self, icon: &str) -> Self {
        self.icon = Some(icon.to_string());
        self
    }

    pub fn with_children(mut self, children: Vec<TreeNode>) -> Self {
        self.children = children;
        self
    }
}

#[derive(Default, UiModel, Serialize, Deserialize, Clone, Debug)]
pub struct Model {
    pub expanded_nodes: Vec<String>,
    pub selected_node: Option<String>,
}

impl Model {
    pub fn new() -> Self {
        Self {
            expanded_nodes: vec!["docs".to_string()],
            selected_node: None,
        }
    }

    pub fn toggle_node(&mut self, node_id: String) {
        if let Some(pos) = self.expanded_nodes.iter().position(|id| id == &node_id) {
            self.expanded_nodes.remove(pos);
        } else {
            self.expanded_nodes.push(node_id);
        }
    }

    pub fn expand_all(&mut self) {
        self.expanded_nodes = vec![
            "docs".to_string(),
            "notes".to_string(),
            "pics".to_string(),
            "vacation".to_string(),
            "music".to_string(),
            "rock".to_string(),
            "jazz".to_string(),
        ];
    }

    pub fn collapse_all(&mut self) {
        self.expanded_nodes.clear();
    }

    pub fn select_node(&mut self, node_id: String) {
        self.selected_node = Some(node_id);
    }
}

#[dampen_ui("tree_view.dampen")]
mod _app {}

pub fn create_app_state() -> AppState<Model> {
    let document = _app::document();
    let handler_registry = create_handler_registry();
    AppState::with_handlers(document, handler_registry)
}

pub fn create_handler_registry() -> HandlerRegistry {
    let registry = HandlerRegistry::new();

    // Toggle node expand/collapse
    registry.register_with_value(
        "toggle_node",
        |model: &mut dyn std::any::Any, params: Box<dyn std::any::Any>| {
            let model = model.downcast_mut::<Model>().unwrap();
            if let Ok(params_str) = params.downcast::<String>() {
                // Parse JSON params like {"node_id":"docs","expanded":true}
                if let Some(node_id) = params_str
                    .split("\"node_id\":\"")
                    .nth(1)
                    .and_then(|s| s.split("\"").next())
                {
                    model.toggle_node(node_id.to_string());
                }
            }
        },
    );

    // Select a node
    registry.register_with_value(
        "select_node",
        |model: &mut dyn std::any::Any, node_id: Box<dyn std::any::Any>| {
            let model = model.downcast_mut::<Model>().unwrap();
            if let Ok(node_id_str) = node_id.downcast::<String>() {
                // Remove quotes from the node_id
                let node_id = node_id_str.trim_matches('"').to_string();
                model.select_node(node_id);
            }
        },
    );

    // Expand all nodes
    registry.register_simple("expand_all", |model: &mut dyn std::any::Any| {
        let model = model.downcast_mut::<Model>().unwrap();
        model.expand_all();
    });

    // Collapse all nodes
    registry.register_simple("collapse_all", |model: &mut dyn std::any::Any| {
        let model = model.downcast_mut::<Model>().unwrap();
        model.collapse_all();
    });

    // Switch back to main window
    registry.register_with_command("switch_to_window", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Window)))
    });

    registry
}
