// Main view UI module.
//
// This file auto-loads the corresponding window.dampen XML file.

use dampen_core::{AppState, HandlerRegistry};
use dampen_macros::{UiModel, dampen_ui};
use serde::{Deserialize, Serialize};

// Import Message and CurrentView from the parent module (generated by macro)
use crate::{CurrentView, Message};

#[derive(Default, UiModel, Serialize, Deserialize, Clone, Debug)]
pub struct Model;

#[dampen_ui("window.dampen")]
mod _app {}

pub fn create_app_state() -> AppState<Model> {
    let document = _app::document();
    let handler_registry = create_handler_registry();
    AppState::with_handlers(document, handler_registry)
}

pub fn create_handler_registry() -> HandlerRegistry {
    let registry = HandlerRegistry::new();

    registry.register_with_command("switch_to_button", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Button)))
    });

    registry.register_with_command("switch_to_canvas", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Canvas)))
    });

    registry.register_with_command("switch_to_text", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Text)))
    });

    registry.register_with_command("switch_to_textinput", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Textinput,
        )))
    });

    registry.register_with_command("switch_to_checkbox", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Checkbox,
        )))
    });

    registry.register_with_command("switch_to_slider", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Slider)))
    });

    registry.register_with_command("switch_to_toggler", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Toggler,
        )))
    });

    registry.register_with_command("switch_to_datetime", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::DatetimePicker,
        )))
    });

    registry.register_with_command(
        "switch_to_color_picker",
        |_model: &mut dyn std::any::Any| {
            Box::new(iced::Task::done(Message::SwitchToView(
                CurrentView::ColorPicker,
            )))
        },
    );

    registry.register_with_command("switch_to_image", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Image)))
    });

    registry.register_with_command("switch_to_svg", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Svg)))
    });

    registry.register_with_command("switch_to_scrollable", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Scrollable,
        )))
    });

    registry.register_with_command("switch_to_stack", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Stack)))
    });

    registry.register_with_command("switch_to_space", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Space)))
    });

    registry.register_with_command("switch_to_layout", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Layout)))
    });

    registry.register_with_command("switch_to_for", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::ForLoop,
        )))
    });

    registry.register_with_command("switch_to_combobox", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Combobox,
        )))
    });

    registry.register_with_command("switch_to_grid", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Grid)))
    });

    registry.register_with_command("switch_to_picklist", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Picklist,
        )))
    });

    registry.register_with_command("switch_to_progressbar", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Progressbar,
        )))
    });

    registry.register_with_command("switch_to_tooltip", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::Tooltip,
        )))
    });

    registry.register_with_command("switch_to_radio", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Radio)))
    });

    registry.register_with_command("switch_to_menu", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(CurrentView::Menu)))
    });

    registry.register_with_command("switch_to_data_table", |_model: &mut dyn std::any::Any| {
        Box::new(iced::Task::done(Message::SwitchToView(
            CurrentView::DataTable,
        )))
    });

    registry
}
